### ISSUE TITLE
[Bug]: shulkers are broken

### ISSUE THREAD

**Issue by CaszGamerMD** [spnda/BlockProt#105]
### Version of BlockProt

1.0 beta 3 \ 1.17.1 paper

### Description of the bug

player places a shulker box, no permission to access, cant pick up, op cant break

### Steps to reproduce

shulker
place
cry.

**Comment by spnda** [comment]
It seems to work fine for me. Do you get any exceptions in the console? Are you sure that all shulker boxes are listed in your `config.yml`?

**Comment by CaszGamerMD** [comment]
Are the permission nodes tied to shulkers in the beta?


Op'd player still couldn't open


I use LP

**Comment by spnda** [comment]
> Are the permission nodes tied to shulkers in the beta?

No, that behaviour has not changed.

I'll ask again: Do you get any exception in the console and could you please check if the shulker boxes are properly listed in `config.yml`?

**Comment by hoehoetvhss** [comment]
In order to work normally, the following phrase should be written in the `config.yml` file.

`
# All varieties of shulker boxes that should be lockable.
lockable_shulker_boxes:
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  `

**Comment by CaszGamerMD** [comment]
Yes everything is correct in config, I get no error

**Comment by hoehoetvhss** [comment]
If there is no problem with the config file, can you check the `Server Console`?

**Comment by hoehoetvhss** [comment]
When I tested, I was able to access and control other players' Shirker boxes, but I couldn't break them unless I unlocked them.

**Comment by spnda** [comment]
If @hoehoetvhss's video is the same bug as @CaszGamerMD described, this is somewhat intended. This issue (or from what I can see) arises because you placed the block before and then destroyed it. The owner/friends/settings are kept after breaking (as it's content is too), so if you then drop it to another player, it will remain locked to you and the other player cannot access it.

Is there any room for improvement here? Any suggestions? Maybe clear the values if it's picked up by another player (possibly configurable through `/blockprot settings`? I'd like to hear some feedback.

**Comment by CaszGamerMD** [comment]
> I'll ask again: Do you get any exception in the console and could you please check if the shulker boxes are properly listed in `config.yml`?

ive been trying to recreate this bug and it seems to be working atm.
when i came across it i reverted back to the 0.4.13 release.
i didn't see anything in the console at the time, and yes config was correct



> If @hoehoetvhss's video is the same bug as @CaszGamerMD described, this is somewhat intended. This issue (or from what I can see) arises because you placed the block before and then destroyed it. The owner/friends/settings are kept after breaking (as it's content is too), so if you then drop it to another player, it will remain locked to you and the other player cannot access it.

i was alone when this happened, i placed a shulker and it said i had no permission when trying to open, or break. so this could very well be what was happening... 

i agree the shulker should have settings
and some kind of communication about shulkers that belong to others so ppl dont place and get stuck

**Comment by August7** [comment]
> 如果@hoehoetvhss的视频与描述@CaszGamerMD相同的错误，那么这在某种程度上是有意为之。这个问题（或从我所看到的）是因为你之前放置了块，然后销毁了它。所有者/好友/设置在中断后保留（因为它的内容也是如此），因此，如果您将其丢弃给其他玩家，它将保持锁定状态，并且其他玩家无法访问它。
> 
> 这方面是否有任何改进的余地？有什么建议吗？如果它被其他玩家拾取，也许可以清除这些值（可能通过？我想听到一些反馈。`/blockprot settings`

If lock_on_place_by_default setting to false, then no one can interact this shulker, including its owner.

**Comment by spnda** [comment]
This has become stale. The behaviour described seems to be intended behaviour and no suggestion/enhancement was made to adjust it. Blocking anyone from accessing shulker boxes even after breaking them guarantees that no items can be stolen. Closing this.
