### ISSUE TITLE
[Question]: Can anyone lock every single chest? 

### ISSUE THREAD

**Issue by Deiia** [spnda/BlockProt#136]
### Your question

Hi! I was wondering if anyone can lock every single chest? If so it should be reading who placed the blocks and only allowing that person to lock it. Otherwise anyone can come to my base and lock my chests?

**Comment by spnda** [comment]
Yes, any player could lock any chests if they are not locked by anyone else. Currently, it is recommended to just lock all of your chests in your base and add any friends to them so that they can be accessed by others. I am also working on making 'public chests' which I am tracking with #125. I am still unsure how I will design that but I think that should also be a better solution to your problem, perhaps?
