### ISSUE TITLE
1.21 support plz

### ISSUE THREAD

**Issue by yanyannnnyan** [spnda/BlockProt#294]
### Feature description

everything works but the friend search feature doesnt when using the 1.20.6 plugin on aternos 1.21 geyser server

**Comment by spnda** [comment]
1.21 support has existed for literally months. Please make sure to open proper issues in the future, with more details and information about the bug. Only because you mentioned Geyser did I know what you might be referring to.

With the newest revision of the plugin there were changes to the friend search feature, and I've encountered a few people who had issues with Geyser players not showing up in the search. This should now be fixed, though I haven't tested this properly.

**Comment by yanyannnnyan** [comment]
im using geyser where it lets bedrock crossover with java, on aternos theres no 1.21 version
nor on curseforge website so i have no idea what you could be talking about
im using 1.2.1 version of the plugin and its listed as to be for 1.20.6 and a bunch of lower versions

**Comment by spnda** [comment]
1.2.0 and 1.2.1 support 1.21. 1.21 just wasn't listed on those sites because I updated before the sites did, so there was no 1.21 checkbox for me to click. I will update the tagging in a second.

I have attached a zip with the most recent change I did, which should allow Geyser players to show up, if that was your problem.
[blockprot-spigot-1.2.1-all.jar.zip](https://github.com/user-attachments/files/16515368/blockprot-spigot-1.2.1-all.jar.zip)

> i click on the paper which is named search user but i only pick it up and nothing happens

Please send me the console output of your server. This sounds like the plugin is crashing, which you did *not* mention before.

**Comment by yanyannnnyan** [comment]
i can try using the one you sent and see if it works

**Comment by yanyannnnyan** [comment]
also i cant dowload files directly to the server if aternos doesnt have it then i cant get it
im trying 1.2.0 bc it said it got 1.21 support

**Comment by yanyannnnyan** [comment]
[New Text Document.txt](https://github.com/user-attachments/files/16515455/New.Text.Document.txt)
heres the log of it

**Comment by yanyannnnyan** [comment]
not that geyser users dont show up 
i click on the paper which says search users but it doesnt do anything, it remains being picked up by my mouse

**Comment by spnda** [comment]
> [New Text Document.txt](https://github.com/user-attachments/files/16515455/New.Text.Document.txt) heres the log of it

Thank you for this, this is what I needed. Turns out this is WesJD/AnvilGUI#343. For now, you should try using Paper instead if that's possible or use an older version of Spigot.

**Comment by yanyannnnyan** [comment]
im not able to change versions bc if the players on my server and plugins that i have so ig we wont use the search feature until its fixed

**Comment by spnda** [comment]
I didn't mean the Minecraft version itself, but the Spigot revision. If it's not possible right now there's a setting in the config to disable the friend search stuff for now, so that nobody abuses it to get unlimited paper.

**Comment by yanyannnnyan** [comment]
the thing is im not able to do that bc it seems like theres only one 1.21 version for it... so yeah gonna disable that ig
if you need me to send more logs of errors let me know

**Comment by yanyannnnyan** [comment]
also it doesnt seem like you can even take the paper, another thing i noticed anything needing searching or renaming also doesnt work, it doesnt trigger that anvil screen to do so
