### ISSUE TITLE
[Bug]: Item lost

### ISSUE THREAD

**Issue by Shiningdark0930** [spnda/BlockProt#296]
### Version of BlockProt

paper 1.2.0 

### Description of the bug

When a hopper with permissions enabled is placed above a block with permissions disabled, items disappear during the process of moving downward through the hopper.

### Steps to reproduce

When a hopper with permissions enabled is placed above a block with permissions disabled, items disappear during the process of moving downward through the hopper.

**Comment by spnda** [comment]
Is there anything showing up in the server console? Any errors? Also could you maybe update the plugin to the latest version to eliminate any other issues?

**Comment by gaborszabo10** [comment]
I have the same issue. I just upgraded to PaperMC 1.21.1 Build 41. I'm using Blockprot 1.2.2. I tried to create some auto crafters that are feed from hoppers. When I put the first lot of items in the hopper, the items disappear immediately, but nothing is coming out of the crafter. When I add more items to the hopper, they just stay in the hopper and don't go into the crafter. When I unlock the hopper, everything works fine. I also tried to add the crafter to the lockable title entities, but I still can't lock the crafter.

**Comment by spnda** [comment]
@gaborszabo10 Do you get any output in the console? In the original revision for 1.21 I had some issues with items disappearing with Crafters, which turned out to be an issue with Spigot itself, which I reported & got fixed.

Could any of you please show me some build with which I could reproduce this issue so I could debug this locally? I need more detailed information before I can figure this out.

**Comment by gaborszabo10** [comment]
I found a workaround. I added the crafter to the lockable blocks list in config and removed it from the lockable tile entities. So now my crafters are locked as well as my hoppers and it is all working. 
I checked and I couldn't see anything in the server logs when I was losing items.
You can try any of the auto crafter builds. I was trying the simplest ones that were compacting. I wanted to get my bone meal to bone blocks. I tried multiple auto crafter builds and the issue was the same with all of them. The first stack of items I put in the hopper just disappeared as if they were sucked out and dropped into the crafter, but I couldn't find them anywhere and the crafter was still empty. All further stacks I placed afterwards just stayed in the hopper. I could reproduce it multiple times, by breaking and replacing the hopper.

**Comment by gaborszabo10** [comment]
I just found the simplest way to reproduce the issue. Place one crafter and then a hopper above it. The first stack of items will disappear from the hopper, only leaving 1 item in there. All further stacks you place will remain. If you break the hopper and put it back, it will do it again. I double checked and I definitely don't get anything in the server logs. I don't have debugging enabled though, only standard logging.
